# Generated by Django 5.1.6 on 2026-03-06 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('maintenance', 'Under Maintenance')], default='available', max_length=20)),
                ('footfall_estimate', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adspaces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
